### ISSUE TITLE
Extending TISSUE with more imputation methods

### ISSUE THREAD

**Issue by pakiessling** [sunericd/TISSUE#1]
Hi there,

fantastic idea for a tool. This looks like excatly what I need!

I am not quite sure which imputation method I will end up using as there are now so many out there.

In case it is not implemented in TISSUE do I understand your code right, that I just have to implement a function in main.py that returns a dataframe with the predicted counts and genes as columns?

Thank you!

**Comment by sunericd** [comment]
Yes, you can modify `main.py` to add new imputation functions. The easiest and safest way would be to add another option to `predict_gene_expression()` (just add to the if statements that are checking `method`) and then from there call an impute function that runs your method and returns the dataframe (same input/output as `spage_impute()`, `tangram_impute()`, etc)
